import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import React, { useState } from 'react';
import { Pressable, StyleSheet, Switch, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Button, Card, DataNotice, Screen } from '../src/components/ui';
import { useTheme } from '../src/theme/ThemeProvider';

function Icon(props: React.ComponentProps<typeof Ionicons>): React.ReactElement { return <Ionicons {...props} accessible={false} accessibilityElementsHidden importantForAccessibility="no-hide-descendants" />; }

export default function IncomeModeScreen(): React.ReactElement {
  const router = useRouter(); const { colors, fontFamily, typography } = useTheme(); const insets = useSafeAreaInsets();
  const [irregular, setIrregular] = useState(true); const [notice, setNotice] = useState<string | null>(null);
  return <Screen contentContainerStyle={{ paddingTop: insets.top + 8 }}>
    <View style={styles.header}><Pressable accessibilityLabel="Go back" accessibilityRole="button" hitSlop={6} onPress={() => router.back()} style={({ pressed }) => [styles.iconButton, { backgroundColor: colors.background.tertiary, opacity: pressed ? .72 : 1 }]}><Icon name="chevron-back" size={20} color={colors.text.primary} /></Pressable><Text style={[styles.headerTitle, { color: colors.text.secondary, fontFamily: fontFamily.medium }]}>Income Engine</Text><View style={styles.iconButton} /></View>
    <View style={styles.hero}><View style={[styles.heroIcon, { backgroundColor: colors.brand.accentLight }]}><Icon name="analytics-outline" size={27} color={colors.semantic.info} /></View><Text style={[styles.eyebrow, { color: colors.semantic.info, fontFamily: fontFamily.semibold }]}>ALGORITHMIC CASHFLOW ANCHORING</Text><Text style={[typography.h2, { color: colors.text.primary }]}>Irregular Income Mode</Text><Text style={[typography.bodySmall, styles.heroCopy, { color: colors.text.tertiary }]}>Anchor essentials to your conservative income floor, then route surplus only when it arrives.</Text></View>
    <Card style={styles.modeCard}><View style={styles.modeRow}><View><Text style={[styles.modeTitle, { color: colors.text.primary, fontFamily: fontFamily.semibold }]}>Irregular / freelance income</Text><Text style={[typography.bodySmall, { color: colors.text.tertiary }]}>Forecasts use a six-month adaptive horizon.</Text></View><Switch accessibilityLabel="Enable irregular income mode" onValueChange={setIrregular} trackColor={{ false: colors.border.strong, true: colors.semantic.income }} value={irregular} /></View><View style={[styles.divider, { backgroundColor: colors.border.subtle }]} /><Text style={[styles.range, { color: colors.text.primary, fontFamily: fontFamily.semibold }]}>5,000 MAD — 9,000 MAD</Text><Text style={[styles.caption, { color: colors.text.tertiary }]}>Estimated monthly trajectory · ±28% volatility</Text></Card>
    <Card style={[styles.floorCard, { borderColor: colors.semantic.income }]}><View style={styles.rowIcon}><Icon name="anchor-outline" size={18} color={colors.semantic.income} /></View><View style={styles.flex}><Text style={[styles.cardTitle, { color: colors.text.primary, fontFamily: fontFamily.semibold }]}>Floor & Upside Architecture</Text><Text style={[typography.bodySmall, { color: colors.text.secondary }]}>Your essential survival budget is anchored to the lowest historical floor: 5,000 MAD. This preview preserves solvency in dry cycles.</Text></View></Card>
    <Text style={[styles.sectionTitle, { color: colors.text.primary, fontFamily: fontFamily.medium }]}>Survival Layer Coverage</Text><Card style={styles.listCard}><Rule icon="home-outline" label="Rent & bills" value="2,600 MAD" /><Rule icon="basket-outline" label="Groceries" value="1,600 MAD" /><Rule icon="shield-outline" label="Buffer" value="800 MAD" /></Card>
    <Text style={[styles.sectionTitle, { color: colors.text.primary, fontFamily: fontFamily.medium }]}>Surplus Routing Logic</Text><Card style={styles.listCard}><Rule icon="shield-checkmark-outline" label="Emergency Buffer" value="85% full" /><Rule icon="receipt-outline" label="Automatic Tax & VAT Sentry" value="30% auto-cut" /><Rule icon="flag-outline" label="Lifestyle & Dream Split" value="70 / 30" /></Card>
    <Card style={[styles.note, { backgroundColor: colors.background.tertiary }]}><Icon name="lock-closed-outline" size={16} color={colors.semantic.info} /><Text style={[typography.bodySmall, styles.flex, { color: colors.text.tertiary }]}>Protected tax vault is excluded from Safe-to-Spend telemetry. These rules are a local preview.</Text></Card>
    <Button label="Simulate Next Payment Split" onPress={() => setNotice('Payment split simulated locally. No routing rules were executed.')} variant="secondary" />
    {notice && <DataNotice label={notice} tone="info" />}
  </Screen>;
}
function Rule({ icon, label, value }: { icon: React.ComponentProps<typeof Ionicons>['name']; label: string; value: string }): React.ReactElement { const { colors, fontFamily } = useTheme(); return <View style={styles.rule}><View style={styles.rowIcon}><Icon name={icon} size={16} color={colors.semantic.info} /></View><Text style={[styles.ruleLabel, { color: colors.text.primary, fontFamily: fontFamily.medium }]}>{label}</Text><Text style={[styles.ruleValue, { color: colors.semantic.income, fontFamily: fontFamily.semibold }]}>{value}</Text></View>; }
const styles = StyleSheet.create({ header:{minHeight:44,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},iconButton:{width:44,height:44,borderRadius:22,alignItems:'center',justifyContent:'center'},headerTitle:{fontSize:12,lineHeight:18},hero:{marginTop:20,alignItems:'center',gap:6},heroIcon:{width:54,height:54,borderRadius:12,alignItems:'center',justifyContent:'center'},eyebrow:{fontSize:10,lineHeight:14},heroCopy:{maxWidth:320,textAlign:'center',lineHeight:19},modeCard:{marginTop:18,padding:14},modeRow:{flexDirection:'row',justifyContent:'space-between',gap:12,alignItems:'center'},modeTitle:{fontSize:13,lineHeight:18},divider:{height:1,marginVertical:12},range:{fontSize:23,lineHeight:30,fontVariant:['tabular-nums']},caption:{marginTop:2,fontSize:10,lineHeight:14},floorCard:{marginTop:12,padding:12,flexDirection:'row',gap:9},rowIcon:{width:32,height:32,borderRadius:8,alignItems:'center',justifyContent:'center'},flex:{flex:1},cardTitle:{fontSize:12,lineHeight:16,marginBottom:4},sectionTitle:{marginTop:22,fontSize:16,lineHeight:22},listCard:{marginTop:8,paddingHorizontal:12},rule:{minHeight:55,flexDirection:'row',alignItems:'center',gap:9},ruleLabel:{flex:1,fontSize:12,lineHeight:16},ruleValue:{fontSize:11,lineHeight:15},note:{marginTop:12,padding:12,flexDirection:'row',gap:9,alignItems:'center'} });