import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Card, DataNotice, Screen } from '../src/components/ui';
import { useTheme } from '../src/theme/ThemeProvider';

function Icon(props: React.ComponentProps<typeof Ionicons>): React.ReactElement { return <Ionicons {...props} accessible={false} accessibilityElementsHidden importantForAccessibility="no-hide-descendants" />; }
export default function PlatformSurfaceScreen(): React.ReactElement { const router = useRouter(); const { colors, fontFamily, typography } = useTheme(); const insets = useSafeAreaInsets(); return <Screen contentContainerStyle={{ paddingTop: insets.top + 8 }}><View style={styles.header}><Pressable accessibilityLabel="Go back" accessibilityRole="button" hitSlop={6} onPress={() => router.back()} style={[styles.headerButton, { backgroundColor: colors.background.tertiary }]}><Icon name="chevron-back" size={20} color={colors.text.primary} /></Pressable><Text style={[styles.headerTitle, { color: colors.text.secondary, fontFamily: fontFamily.medium }]}>Platform Surface</Text><View style={styles.headerButton} /></View><Text style={[styles.eyebrow, { color: colors.semantic.info, fontFamily: fontFamily.semibold }]}>LOCK SCREEN & DYNAMIC ISLAND · REFERENCE</Text><Text style={[typography.h2, { color: colors.text.primary, marginTop: 5 }]}>Ambient financial awareness</Text><Text style={[typography.bodySmall, { color: colors.text.tertiary, marginTop: 4 }]}>A native surface concept for moments when the app is not open.</Text><DataNotice icon="information-circle-outline" label="Reference only · native lock-screen and Dynamic Island APIs are not active in this build" tone="warning" /><Card style={styles.phone}><View style={styles.island}><View style={[styles.dot, { backgroundColor: colors.semantic.income }]} /><Text style={[styles.islandText, { color: colors.text.inverse, fontFamily: fontFamily.semibold }]}>Lyvora · Safe-to-Spend</Text></View><View style={styles.lockContent}><Text style={[styles.time, { color: colors.text.primary, fontFamily: fontFamily.semibold }]}>09:41</Text><Text style={[styles.date, { color: colors.text.tertiary }]}>Tuesday, 15 October</Text><View style={[styles.alert, { borderColor: colors.semantic.income }]}><Icon name="shield-checkmark-outline" size={20} color={colors.semantic.income} /><View style={styles.flex}><Text style={[styles.alertTitle, { color: colors.text.primary, fontFamily: fontFamily.semibold }]}>You are covered</Text><Text style={[styles.small, { color: colors.text.tertiary }]}>Safe-to-Spend 2,450 MAD · no urgent bills</Text></View></View></View></Card><Card style={styles.notes}><Text style={[styles.section, { color: colors.text.primary, fontFamily: fontFamily.semibold }]}>Native handoff</Text><Text style={[styles.small, { color: colors.text.tertiary }]}>The eventual implementation belongs in Android lock-screen notification and live-surface integrations. This preview defines the content contract without claiming OS-level behavior.</Text></Card></Screen>; }
const styles = StyleSheet.create({ header: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, headerButton: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' }, headerTitle: { fontSize: 12, lineHeight: 18 }, eyebrow: { marginTop: 22, fontSize: 10, lineHeight: 14 }, phone: { marginTop: 16, minHeight: 260, padding: 14, backgroundColor: '#111B2C', borderColor: '#263A57', overflow: 'hidden' }, island: { alignSelf: 'center', minHeight: 34, paddingHorizontal: 13, borderRadius: 18, backgroundColor: '#050A13', flexDirection: 'row', alignItems: 'center', gap: 7 }, dot: { width: 7, height: 7, borderRadius: 4 }, islandText: { fontSize: 10, lineHeight: 14 }, lockContent: { flex: 1, alignItems: 'center', justifyContent: 'center' }, time: { fontSize: 48, lineHeight: 58 }, date: { fontSize: 11, lineHeight: 16 }, alert: { width: '100%', marginTop: 28, padding: 13, borderWidth: 1, borderRadius: 10, flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#18263A' }, flex: { flex: 1 }, alertTitle: { fontSize: 13, lineHeight: 18 }, small: { fontSize: 10, lineHeight: 15 }, notes: { marginTop: 14, padding: 14 }, section: { fontSize: 16, lineHeight: 22, marginBottom: 5 } });