import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import React, { useState } from 'react';
import { Pressable, StyleSheet, Switch, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Card, DataNotice, Screen } from '../src/components/ui';
import { useTheme } from '../src/theme/ThemeProvider';

type Scope = 'full' | 'limited' | 'none';

function DecorativeIcon(props: React.ComponentProps<typeof Ionicons>): React.ReactElement {
  return <Ionicons {...props} accessible={false} accessibilityElementsHidden importantForAccessibility="no-hide-descendants" />;
}

export default function PrivacyScreen(): React.ReactElement {
  const router = useRouter();
  const { colors, fontFamily, typography } = useTheme();
  const insets = useSafeAreaInsets();
  const [scope, setScope] = useState<Scope>('full');
  const [autoCategorize, setAutoCategorize] = useState(true);
  const [alerts, setAlerts] = useState(true);
  const [notice, setNotice] = useState<string | null>(null);
  const selectScope = (nextScope: Scope) => { setScope(nextScope); setNotice(`AI context scope changed locally to ${nextScope === 'full' ? 'Full Financial Context' : nextScope === 'limited' ? 'Transactions & Categories Only' : 'No Financial AI'}.`); };

  return <Screen contentContainerStyle={{ paddingTop: insets.top + 8 }}>
    <View style={styles.header}><Pressable accessibilityLabel="Go back" accessibilityRole="button" hitSlop={6} onPress={() => router.back()} style={({ pressed }) => [styles.iconButton, { backgroundColor: colors.background.tertiary, opacity: pressed ? 0.72 : 1 }]}><DecorativeIcon name="chevron-back" size={20} color={colors.text.primary} /></Pressable><Text style={[styles.headerTitle, { color: colors.text.secondary, fontFamily: fontFamily.medium }]}>Privacy Settings</Text><View style={styles.iconButton} /></View>
    <View style={styles.hero}><View style={[styles.heroIcon, { backgroundColor: colors.semantic.incomeLight }]}><DecorativeIcon name="shield-checkmark-outline" size={27} color={colors.semantic.income} /></View><Text style={[styles.eyebrow, { color: colors.semantic.info, fontFamily: fontFamily.semibold }]}>SECURITY & GOVERNANCE</Text><Text style={[typography.h2, { color: colors.text.primary }]}>Privacy & AI Access</Text><Text style={[typography.bodySmall, styles.heroCopy, { color: colors.text.tertiary }]}>Financial context is encrypted at rest and is never used to train or monetize Lyvora models.</Text></View>
    <Card style={[styles.vaultCard, { borderColor: colors.semantic.income }]}><View style={[styles.vaultIcon, { backgroundColor: colors.semantic.incomeLight }]}><DecorativeIcon name="lock-closed-outline" size={18} color={colors.semantic.income} /></View><View style={styles.vaultCopy}><Text style={[styles.vaultTitle, { color: colors.text.primary, fontFamily: fontFamily.semibold }]}>Cryptographic Vault: Active</Text><Text style={[typography.bodySmall, { color: colors.text.tertiary }]}>Device-key encryption · ephemeral AI tokenization · zero permanent context cache</Text></View></Card>
    <Text style={[styles.sectionTitle, { color: colors.text.primary, fontFamily: fontFamily.medium }]}>AI Context Scope</Text><Text style={[styles.sectionSubtitle, { color: colors.text.tertiary }]}>Choose what Lyvora can inspect. Changes apply locally in this preview.</Text>
    <ScopeCard active={scope === 'full'} description="Balances, goals, salary cycles, and transaction history for liquidity and forecast calculations." icon="analytics-outline" onPress={() => selectScope('full')} title="Full Financial Context" tone="info" />
    <ScopeCard active={scope === 'limited'} description="Transaction categories and receipts only. Lyvora cannot view balances, net worth, or goals." icon="receipt-outline" onPress={() => selectScope('limited')} title="Transactions & Categories Only" tone="income" />
    <ScopeCard active={scope === 'none'} description="Disables Copilot, voice chat, and predictive simulations. Manual ledger only." icon="hand-left-outline" onPress={() => selectScope('none')} title="No Financial AI" tone="warning" />
    <Text style={[styles.sectionTitle, { color: colors.text.primary, fontFamily: fontFamily.medium }]}>Automation & Execution Permissions</Text>
    <Card style={styles.permissionCard}><PermissionRow description="High-confidence transaction classification only." label="Auto-categorize transactions" onChange={setAutoCategorize} value={autoCategorize} /><View style={[styles.divider, { backgroundColor: colors.border.subtle }]} /><PermissionRow description="Scans recurring charges for fee increases." label="Intelligent push alerts" onChange={setAlerts} value={alerts} /><View style={[styles.divider, { backgroundColor: colors.border.subtle }]} /><View style={styles.permissionRow}><View style={styles.permissionCopy}><Text style={[styles.permissionLabel, { color: colors.text.primary, fontFamily: fontFamily.medium }]}>Auto-transfer money to savings</Text><Text style={[styles.permissionDescription, { color: colors.text.tertiary }]}>Unavailable. Every transfer requires explicit approval and a supported account connection.</Text></View><View style={[styles.blockedPill, { backgroundColor: colors.semantic.warningLight }]}><Text style={[styles.blockedText, { color: colors.semantic.warning, fontFamily: fontFamily.medium }]}>Approval required</Text></View></View></Card>
    <Card style={[styles.auditCard, { backgroundColor: colors.background.tertiary }]}><DecorativeIcon name="receipt-outline" size={17} color={colors.semantic.info} /><View style={styles.auditCopy}><Text style={[styles.vaultTitle, { color: colors.text.primary, fontFamily: fontFamily.medium }]}>Review AI Audit Log</Text><Text style={[typography.bodySmall, { color: colors.text.tertiary }]}>7 ephemeral requests this billing period. Revoking access discards local cache and active session tokens.</Text></View></Card>
    {notice && <DataNotice label={notice} tone="info" />}
  </Screen>;
}

function ScopeCard({ active, description, icon, onPress, title, tone }: { active: boolean; description: string; icon: React.ComponentProps<typeof Ionicons>['name']; onPress: () => void; title: string; tone: 'income' | 'warning' | 'info' }): React.ReactElement {
  const { colors, fontFamily, typography } = useTheme(); const color = colors.semantic[tone];
  return <Pressable accessibilityLabel={`Select ${title}`} accessibilityRole="radio" accessibilityState={{ selected: active }} onPress={onPress} style={({ pressed }) => [styles.scopeCard, { backgroundColor: colors.background.card, borderColor: active ? color : colors.border.default, opacity: pressed ? 0.72 : 1 }]}><View style={[styles.scopeIcon, { backgroundColor: tone === 'income' ? colors.semantic.incomeLight : tone === 'warning' ? colors.semantic.warningLight : colors.brand.accentLight }]}><DecorativeIcon name={icon} size={18} color={color} /></View><View style={styles.scopeCopy}><Text style={[styles.scopeTitle, { color: colors.text.primary, fontFamily: fontFamily.semibold }]}>{title}</Text><Text style={[typography.bodySmall, { color: colors.text.tertiary }]}>{description}</Text></View><View style={[styles.radio, { borderColor: active ? color : colors.border.strong }]}>{active && <View style={[styles.radioFill, { backgroundColor: color }]} />}</View></Pressable>;
}

function PermissionRow({ description, label, onChange, value }: { description: string; label: string; onChange: (value: boolean) => void; value: boolean }): React.ReactElement {
  const { colors, fontFamily } = useTheme(); return <View style={styles.permissionRow}><View style={styles.permissionCopy}><Text style={[styles.permissionLabel, { color: colors.text.primary, fontFamily: fontFamily.medium }]}>{label}</Text><Text style={[styles.permissionDescription, { color: colors.text.tertiary }]}>{description}</Text></View><Switch accessibilityLabel={label} onValueChange={onChange} trackColor={{ false: colors.border.strong, true: colors.semantic.income }} value={value} /></View>;
}

const styles = StyleSheet.create({
  header: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, iconButton: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' }, headerTitle: { fontSize: 12, lineHeight: 18 }, hero: { marginTop: 20, alignItems: 'center', gap: 6 }, heroIcon: { width: 54, height: 54, borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginBottom: 4 }, eyebrow: { fontSize: 10, lineHeight: 14 }, heroCopy: { maxWidth: 320, textAlign: 'center', lineHeight: 19 }, vaultCard: { marginTop: 18, padding: 12, flexDirection: 'row', gap: 9 }, vaultIcon: { width: 38, height: 38, borderRadius: 8, alignItems: 'center', justifyContent: 'center' }, vaultCopy: { flex: 1, gap: 4 }, vaultTitle: { fontSize: 11, lineHeight: 15 }, sectionTitle: { marginTop: 22, fontSize: 16, lineHeight: 22 }, sectionSubtitle: { marginTop: 3, fontSize: 10, lineHeight: 14 }, scopeCard: { minHeight: 86, marginTop: 8, borderWidth: 1, borderRadius: 8, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 9 }, scopeIcon: { width: 34, height: 34, borderRadius: 8, alignItems: 'center', justifyContent: 'center' }, scopeCopy: { flex: 1, gap: 3 }, scopeTitle: { fontSize: 12, lineHeight: 16 }, radio: { width: 20, height: 20, borderWidth: 2, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, radioFill: { width: 10, height: 10, borderRadius: 5 }, permissionCard: { marginTop: 8, paddingHorizontal: 12 }, permissionRow: { minHeight: 70, flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 10 }, permissionCopy: { flex: 1, gap: 3 }, permissionLabel: { fontSize: 11, lineHeight: 15 }, permissionDescription: { fontSize: 9, lineHeight: 13 }, divider: { height: 1 }, blockedPill: { borderRadius: 10, paddingHorizontal: 7, paddingVertical: 4 }, blockedText: { fontSize: 9, lineHeight: 13, textAlign: 'center' }, auditCard: { marginTop: 12, padding: 12, flexDirection: 'row', gap: 9 }, auditCopy: { flex: 1, gap: 4 },
});