import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import React, { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Button, Card, DataNotice, Screen } from '../src/components/ui';
import { useTheme } from '../src/theme/ThemeProvider';

function Icon(props: React.ComponentProps<typeof Ionicons>): React.ReactElement { return <Ionicons {...props} accessible={false} accessibilityElementsHidden importantForAccessibility="no-hide-descendants" />; }

export default function VaultScreen(): React.ReactElement {
  const router = useRouter(); const { colors, fontFamily, typography } = useTheme(); const insets = useSafeAreaInsets(); const [reviewed, setReviewed] = useState(false);
  return <Screen contentContainerStyle={{ paddingTop: insets.top + 8 }}><View style={styles.header}><Pressable accessibilityLabel="Go back" accessibilityRole="button" hitSlop={6} onPress={() => router.back()} style={[styles.headerButton, { backgroundColor: colors.background.tertiary }]}><Icon name="chevron-back" size={20} color={colors.text.primary} /></Pressable><Text style={[styles.headerTitle, { color: colors.text.secondary, fontFamily: fontFamily.medium }]}>Document Vault</Text><View style={styles.headerButton} /></View><Text style={[styles.eyebrow, { color: colors.semantic.info, fontFamily: fontFamily.semibold }]}>DOCUMENT VAULT · PREVIEW</Text><Text style={[typography.h2, { color: colors.text.primary, marginTop: 5 }]}>Your financial memory</Text><Text style={[typography.bodySmall, { color: colors.text.tertiary, marginTop: 4 }]}>Receipts, statements, and contracts organized for future decisions.</Text><DataNotice icon="eye-outline" label="Design preview · documents are sample records and are not uploaded" tone="info" /><Card style={styles.secureCard}><View style={[styles.lock, { backgroundColor: colors.semantic.incomeLight }]}><Icon name="lock-closed-outline" size={23} color={colors.semantic.income} /></View><View style={styles.flex}><Text style={[styles.title, { color: colors.text.primary, fontFamily: fontFamily.semibold }]}>Vault protected</Text><Text style={[styles.small, { color: colors.text.tertiary }]}>0 external files connected · local review only</Text></View><Text style={[styles.status, { color: colors.semantic.income, fontFamily: fontFamily.semibold }]}>READY</Text></Card><Text style={[styles.section, { color: colors.text.primary, fontFamily: fontFamily.semibold }]}>Recent records</Text><Card style={styles.card}><Document icon="receipt-outline" title="March household receipt" detail="Added for categorization · 2 pages" /><Document icon="document-text-outline" title="Bank statement · February" detail="Reference copy · ending 4821" /><Document icon="contract-outline" title="Apartment insurance policy" detail="Renewal review · Oct 2026" last /></Card><Card style={[styles.insight, { borderColor: colors.brand.accent }]}><Icon name="sparkles-outline" size={18} color={colors.semantic.info} /><View style={styles.flex}><Text style={[styles.title, { color: colors.text.primary, fontFamily: fontFamily.semibold }]}>Vault insight</Text><Text style={[styles.small, { color: colors.text.tertiary }]}>A renewal date is approaching. Review it before the next planning cycle.</Text></View></Card>{reviewed ? <Card style={styles.confirmation}><DataNotice icon="checkmark-circle-outline" label="Vault review prepared locally. No file was uploaded or shared." tone="info" /></Card> : <Button icon="search-outline" label="Prepare vault review" onPress={() => setReviewed(true)} style={styles.action} />}</Screen>;
}

function Document({ icon, title, detail, last = false }: { icon: React.ComponentProps<typeof Ionicons>['name']; title: string; detail: string; last?: boolean }): React.ReactElement { const { colors, fontFamily } = useTheme(); return <View style={[styles.row, !last && { borderBottomColor: colors.border.subtle, borderBottomWidth: 1 }]}><View style={[styles.docIcon, { backgroundColor: colors.background.tertiary }]}><Icon name={icon} size={18} color={colors.text.secondary} /></View><View style={styles.flex}><Text style={[styles.title, { color: colors.text.primary, fontFamily: fontFamily.semibold }]}>{title}</Text><Text style={[styles.small, { color: colors.text.tertiary }]}>{detail}</Text></View><Icon name="chevron-forward" size={17} color={colors.text.tertiary} /></View>; }

const styles = StyleSheet.create({ header: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, headerButton: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' }, headerTitle: { fontSize: 12, lineHeight: 18 }, eyebrow: { marginTop: 22, fontSize: 10, lineHeight: 14 }, secureCard: { marginTop: 16, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 10 }, lock: { width: 44, height: 44, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, flex: { flex: 1 }, title: { fontSize: 12, lineHeight: 17 }, small: { fontSize: 10, lineHeight: 14 }, status: { fontSize: 9, lineHeight: 14 }, section: { marginTop: 22, fontSize: 16, lineHeight: 22 }, card: { marginTop: 8, paddingHorizontal: 12 }, row: { minHeight: 72, flexDirection: 'row', alignItems: 'center', gap: 10 }, docIcon: { width: 38, height: 38, borderRadius: 8, alignItems: 'center', justifyContent: 'center' }, insight: { marginTop: 14, padding: 14, flexDirection: 'row', gap: 10 }, confirmation: { marginTop: 14, padding: 14 }, action: { marginTop: 14 }, });